# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd frontend && yarn install
    - run: cd frontend && yarn build
    - run: cd tests && yarn install
    - run: cd tests && ./node_modules/.bin/chromedriver -v
    - run: docker-compose build projectx
    - run: docker-compose up -d
    - run: docker-compose exec -T projectx /home/user/venv/bin/python /home/user/backend/app/manage.py wait_for_db
    - run: cd tests && yarn test
